
env:
   global:
     - CONAN_REFERENCE: "Poco/1.9.0"
     - CONAN_USERNAME: "sago"
     - CONAN_LOGIN_USERNAME: "user"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://sago.bintray.com/sago-conan"

linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang70

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
