env:
  global:
    - CONAN_REFERENCE="Poco/1.9.0"
    - CONAN_USERNAME="sago"
    - CONAN_LOGIN_USERNAME="suwei-air"
    - CONAN_CHANNEL="testing"
    - CONAN_UPLOAD="https://api.bintray.com/conan/sago/sago-conan"
    - CONAN_ARCHS="x86_64"
    - CONAN_BUILD_TYPES="Release"

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: 3.7
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
      packages:
        - clang-7
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0

    - <<: *osx
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
