env:
  global:
    - CONAN_REFERENCE="Poco/1.9.0"
    - CONAN_USERNAME="sago"
    - CONAN_LOGIN_USERNAME="suwei-air"
    - CONAN_CHANNEL="testing"
    - CONAN_UPLOAD="https://api.bintray.com/conan/sago/sago-conan"
    - CONAN_BUILD_TYPES="Release"

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - CONAN_ARCHS="x86_64"
        - CONAN_CLANG_VERSIONS="7.0"

    - language: android
      android:
        components:
          - tools
          - platform-tools
      before_install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - virtualenv venv
        - source venv/bin/activate
        - export CONAN_BASE_PROFILE="$(pwd)/profile/Android.profile"
        - export PATH="$ANDROID_HOME/cmake/3.10.2.4988404/bin:$PATH"
      env:
        - CONAN_ARCHS="armv7"
        - CONAN_CLANG_VERSIONS="7.0"

    - os: osx
      osx_image: xcode10
      language: generic
      env:
        - CONAN_ARCHS="x86_64"
        - CONAN_APPLE_CLANG_VERSIONS="10.0"

    - os: osx
      osx_image: xcode10
      language: generic
      before_install:
        - export CONAN_BASE_PROFILE="$(pwd)/profile/iOS.profile"
      env:
        - CONAN_ARCHS="armv7"
        - CONAN_APPLE_CLANG_VERSIONS="10.0"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
