build: false

environment:
  PYTHON: "C:\\Python37"

  CONAN_REFERENCE: "Poco/1.9.0"
  CONAN_USERNAME: "sago"
  CONAN_LOGIN_USERNAME: "suwei-air"
  CONAN_CHANNEL: "testing"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sago/sago-conan"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15

install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
